apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lslab4-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "128Mi"
    limits:
      storage: "1Gi"