apiVersion: apps/v1
kind: Deployment
metadata:
  name: secondnsdeployment
  namespace: ns2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lslab4
  template:
    metadata:
      labels:
        app: lslab4
    spec:
      containers:
        - name: app
          image: nginx