apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lslab4-sts
  labels:
    app: lslab4
spec:
  serviceName: lslab4-sts
  replicas: 5
  revisionHistoryLimit: 100
  selector:
    matchLabels:
      app: lslab4
  template:
    metadata:
      labels:
        app: lslab4
    spec:
      containers:
        - name: app
          image: supersloy/lslab4:latest
          env:
          - name: CATS
            valueFrom:
              configMapKeyRef:
                name: lslab4-configmap
                key: CATS
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: lslab4-configmap
                key: PORT
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: lslab4-secret
                key: API_KEY
          volumeMounts:
            - name: data
              mountPath: /usr/src/app/data
          ports:
            - containerPort: 8080
      # volumes:
      #   - name: data
      #     persistentVolumeClaim:
      #       claimName: lslab4-pvc
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 128Mi